spring:
  datasource:
    url: jdbc:p6spy:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
  batch:
    jdbc:
      initialize-schema: always
mybatis:
  mapper-locations: classpath:/mybatis/mappers/**/*.xml
  type-aliases-package: com.example.batch.entity
  config-location:
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    p6spy: DEBUG
    com.p6spy: DEBUG