spring:
  batch:
    jdbc:
      initialize-schema: always
mybatis:
  mapper-locations: classpath:/mybatis/mappers/**/*.xml
  type-aliases-package: com.example.batch.entity
  config-location:
decorator:
  datasource:
    p6spy:
      enable-logging: true
