spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/batch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: schema-all.sql
