spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    org.mybatis: DEBUG
    org.springframework.jdbc.core: DEBUG