spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 자동 Batch Job ID 생성 방지
mybatis:
  mapper-locations: classpath:/mybatis/mappers/**/*.xml
  type-aliases-package: com.example.batch.domain
  configuration:
    log-impl: com.example.batch.core.log.CustomMyBatisLoggerImpl
logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG